# Generated by Django 4.2.7 on 2026-03-03 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_latitude_clientprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='aadhaar_card',
            field=models.FileField(blank=True, help_text='Aadhaar card document (PDF or image, max 5MB)', null=True, upload_to='vendor/aadhaar_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='ewaste_auth_id',
            field=models.CharField(blank=True, help_text='ID number on the e-waste authorization document', max_length=50),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='ewaste_auth_type',
            field=models.CharField(choices=[('cpcb', 'CPCB Recycler Registration'), ('spcb', 'SPCB Consent to Operate (CTO)'), ('hazardous', 'Hazardous Waste Authorization')], default='cpcb', help_text='Type of e-waste authorization document', max_length=20),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='pan_card',
            field=models.FileField(blank=True, help_text='PAN card document (PDF or image, max 5MB)', null=True, upload_to='vendor/pan_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='use_registration_details',
            field=models.BooleanField(default=True, help_text='Use details provided during registration (Name/Phone)'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='ewaste_authorization',
            field=models.FileField(blank=True, help_text='Authorized recycling document (PDF or image, max 5MB)', null=True, upload_to='vendor/ewaste_auth/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
