# Generated by Django 4.2.7 on 2026-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_clientprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of the business owner/contact', null=True),
        ),
    ]
